name: try-jupyter
channels:
- conda-forge
dependencies:
- python =3.11
- mamba
- pydata-sphinx-theme
- myst-parser
- bqplot
- ipycanvas >=0.9.1
- ipyleaflet
- ipympl >=0.8.2
- ipywidgets >=8.1.1,<9
- jupyterlab >=4.3.4,<=4.4
- jupyterlab-language-pack-fr-FR
- jupyterlab-language-pack-zh-CN
- jupyterlab-fasta >=3.3.0,<4
- jupyterlab-geojson >=3.4.0,<4
- jupyterlab-tour
- jupyterlab-night
- jupyterlite-core =0.5.0
- jupyterlite-pyodide-kernel =0.5.0
- jupyterlite-sphinx >=0.18.0,<0.19
- notebook >=7.3.2,<7.4
- pip
- plotly >=5,<6
- pip:
  - jupyterlite-xeus-sqlite==0.2.1
  - jupyterlab-open-url-parameter >=0.3.0
